version: "3.8"
services:
    nginx:
        build: ./docker/nginx
        ports:
            - "${NGINX_HTTP_PORT}:80"
            - "${NGINX_HTTPS_PORT}:443"
        volumes:
            - ./src/public:/usr/src/app/public
        depends_on:
            - php-customer
            - php-client
            - php-admin
            - php-api
        networks:
            - glc
    php-api:
      build: ./docker/php-fpm
      volumes:
        - ./src:/usr/src/app
        - ./src/.env.api:/usr/src/app/.env
      networks:
        - glc
    php-customer:
        build: ./docker/php-fpm
        volumes:
            - ./src:/usr/src/app
            - ./src/.env.customer:/usr/src/app/.env
        networks:
            - glc
    php-client:
        build: ./docker/php-fpm
        volumes:
            - ./src:/usr/src/app
            - ./src/.env.client:/usr/src/app/.env
        networks:
            - glc
    php-admin:
        build: ./docker/php-fpm
        volumes:
            - ./src:/usr/src/app
            - ./src/.env.master:/usr/src/app/.env
        networks:
            - glc
    node:
        build: ./docker/node
        volumes:
            - ./src:/usr/src/app
        command: >
            bash -c "/usr/local/init.sh"
    mysql:
        platform: linux/amd64 # Apple silicon対応
        build: docker/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - glc
    redis:
        build: ./docker/redis
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - redis:/data
        networks:
            - glc
    mailcatcher:
        build: ./docker/mailcatcher
        ports:
            - "${MAILCATCHER_PORT}:1080"
        networks:
            - glc
    minio:
        build: ./docker/minio
        ports:
            - "${MINIO_PORT}:9000"
            - "${MINIO_CONSOLE_PORT}:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        volumes:
            - minio:/data
        networks:
            - glc
volumes:
    mysql:
    redis:
    minio:
networks:
    glc:
